In [32]:
import numpy as np
from scipy.sparse import (csr_matrix, csr_matrix, coo_matrix,
                bsr_matrix, dia_matrix, dok_matrix, lil_matrix)
from numpy.random import rand
from time import time
import random

n = 10000 # dimension of matrix

# List of Lists format (lil_matrix)

Create a list of list matrix that is of size n x n.  We will fill that one with random values.  Also create lil matrix that is identity.

In [33]:
lil1 = lil_matrix((n,n))
lilIdentity = lil_matrix((n,n))

Fill the first one hundred values of the zeroth row with random numbers over the distribution [0, 1).  Then fill the diagonal also with random numbers.

In [34]:
lil1[0, :100] = rand(100)
lil1.setdiag(rand(n))


Fill in the identity matrix.

In [35]:
for i in range(n):
    lilIdentity[i,i] = 1

See how long it takes to multiply a lil matrix with another lil matrix.

In [36]:
time1 = time()
lil1 = lil1*lilIdentity
print("Time(s) for lil multiply: " + str(time() - time1))

Time(s) for lil multiply: 0.004474163055419922


Convert them to dense matrices and see how long the multiply takes.

In [37]:
dense1 = lil1.toarray()
denseIdentity = lilIdentity.toarray()
time1 = time()
dense1 = dense1 * denseIdentity
print("Time(s) for dense multiple: " + str(time() - time1))

Time(s) for dense multiple: 1.6002421379089355


Now how does adding matrices compare?

In [38]:
lil2 = lil1
time1 = time()
lil2 = lil2 + lil2
print("Time(s) for lil add: " + str(time() - time1))

Time(s) for lil add: 0.0006101131439208984


In [39]:
dense1 = lil1.toarray()
denseIdentity = lilIdentity.toarray()
time1 = time()
dense1 = dense1 + dense1
print("Time(s) for dense add: " + str(time() - time1))

Time(s) for dense add: 0.6401793956756592


What happens when a lil matrix has many values?

In [40]:
lilManyValues = lil_matrix((n,n))
numValues = int(n*n / 10)
for iter in range(numValues):
    i = random.randrange(n)
    j = random.randrange(n)
    lilManyValues[i,j] = 1
print("Fraction nonzero: " + str(lilManyValues.count_nonzero() / (n*n)))
    
time1 = time()
lilManyValues = lilManyValues * lilManyValues
print("Time for lil multiply: " + str(time() - time1))

denseManyValues = lilManyValues.toarray()
time1 = time()
denseManyValues = denseManyValues * denseManyValues
print("Time for dense multiply: " + str(time() - time1))

Fraction nonzero: 0.09516356
Time for lil multiply: 28.344743967056274
Time for dense multiply: 0.449354887008667


# Compressed Sparse Row (csr_matrix) and Compressed Sparse Column (csc_matrix)

In [41]:
csr1 = lil1.tocsr()
csc1 = lil1.tocsc()
csrIdentity = lilIdentity.tocsr()
cscIdentity = lilIdentity.tocsc()

In [42]:
time1 = time()
csr1 = csr1*csr1
print("Time(s) for csr multiply: " + str(time() - time1))

Time(s) for csr multiply: 0.0008141994476318359


In [43]:
csr2 = csr1
time1 = time()
csr2 = csr2 + csr2
print("Time(s) for csr add: " + str(time() - time1))

Time(s) for csr add: 0.0004820823669433594


In [44]:
iters = 10000
time1 = time()
for i in range(iters):
    index = random.randrange(n)
    row = csr1[index,:]
    nnz = row.count_nonzero()
print("Time(s) for accessing rows: " + str(time() - time1))
for i in range(iters):
    index = random.randrange(n)
    row = csr1[:,index]
    nnz = row.count_nonzero()
print("Time(s) for accessing columns: " + str(time() - time1))


Time(s) for accessing rows: 0.869877815246582
Time(s) for accessing columns: 2.2714409828186035


In [45]:
iters = 10000
time1 = time()
for i in range(iters):
    index = random.randrange(n)
    row = csc1[index,:]
    nnz = row.count_nonzero()
print("Time(s) for accessing rows: " + str(time() - time1))
for i in range(iters):
    index = random.randrange(n)
    row = csc1[:,index]
    nnz = row.count_nonzero()
print("Time(s) for accessing columns: " + str(time() - time1))

Time(s) for accessing rows: 1.4538440704345703
Time(s) for accessing columns: 2.289771795272827


# Hindom Optimization Equation 

F(t+1)=(1/(1+mu)) D^(-1/2) M' D^(-1/2) F(t) + (mu/(1+mu)) Y

Create something that looks like M' of Hindom.

In [46]:
n = 100 
M = lil_matrix((n,n))
numValues = 500
for iter in range(numValues):
    i = random.randrange(n)
    j = random.randrange(n)
    M[i,j] = random.random() # [0,1)
print("Fraction nonzero: " + str(M.count_nonzero() / (n*n)))
M = M.tocsr()

Fraction nonzero: 0.0485


Actually have to create an affinity matrix.

In [47]:
import math
W = M.toarray()
for i in range(n):
    for j in range(n):
        if i == j:
            W[i,j] = 0
        else:
            W[i,j] = math.exp(-np.linalg.norm(M[i,:].toarray() - M[j,:].toarray(), ord=2))
M = W
print(M.shape)

(100, 100)


Create diagonal matrix D

In [49]:
data = np.squeeze(np.asarray(M.sum(axis=1))) # sum the rows
offsets = np.array([0])
D = dia_matrix((data, offsets), shape=(n,n))

Calculate the exponent (-1/2), which is easy for a diagonal.  We can just take each diagonal element and raise it to (-1/2).

In [50]:
D = D.tocsr() # Convert to csr because can't use subscripting
for i in range(n):
    D[i,i] = D[i,i] ** (-1/2) 

Create the matrix S

In [51]:
S = D * M * D

mu is just how we weight each piece, smoothness vs fidelity to known labels

In [52]:
mu = 0.5
alpha = 1/(1 + mu)
beta = mu/(1 + mu)

Create some labels. 

In [53]:
Y = np.zeros((n,2))
# Set some to be malicious and benign
for i in range(int(n/10)):
    index = random.randrange(n)
    if i % 2 == 0:
        Y[index,0] = 1
        Y[index,1] = 0
    else:
        Y[index,0] = 0
        Y[index,1] = 1

Set F to be Y.

In [54]:
F = Y
print(F)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]]


Do one iteration

In [55]:
F = alpha * S.dot(F) + beta * Y
print(F)

[[0.03279323 0.04214085]
 [0.03530374 0.0401057 ]
 [0.03001225 0.02960493]
 [0.02658198 0.02888225]
 [0.02903081 0.03233552]
 [0.03352022 0.03766214]
 [0.03252847 0.0370791 ]
 [0.03426363 0.03545973]
 [0.02938819 0.03269118]
 [0.03022702 0.03272619]
 [0.02479133 0.02502719]
 [0.02772989 0.0317721 ]
 [0.03468009 0.03892743]
 [0.0289314  0.0291541 ]
 [0.02884585 0.03098009]
 [0.03461008 0.03501924]
 [0.02974642 0.03084751]
 [0.02256764 0.02437958]
 [0.03398196 0.03198979]
 [0.03219891 0.03340883]
 [0.02835941 0.03030526]
 [0.03069409 0.03350738]
 [0.04041481 0.03408019]
 [0.0274529  0.03205934]
 [0.35199174 0.02520193]
 [0.02866116 0.03091169]
 [0.35823147 0.03027133]
 [0.03336012 0.03512675]
 [0.03328917 0.03764202]
 [0.0297834  0.03336051]
 [0.36015311 0.02970424]
 [0.01950008 0.01947553]
 [0.02963444 0.03197736]
 [0.0281661  0.0300264 ]
 [0.03116287 0.03408665]
 [0.02743225 0.02941426]
 [0.03026809 0.03281845]
 [0.02655485 0.02856489]
 [0.03177584 0.03451249]
 [0.03277161 0.03681554]


In [56]:
for i in range(10000):
  F = alpha * S.dot(F) + beta * Y
  
print(F)

[[0.03356588 0.03836037]
 [0.03674686 0.04023443]
 [0.0287061  0.0299738 ]
 [0.02666772 0.02875631]
 [0.02885671 0.03138589]
 [0.03496911 0.03813806]
 [0.03211163 0.03521569]
 [0.03363772 0.03570972]
 [0.02965683 0.03224355]
 [0.03055308 0.03292165]
 [0.02456115 0.02584642]
 [0.02837579 0.03114527]
 [0.03592283 0.03917608]
 [0.02840968 0.02989552]
 [0.02952351 0.03171736]
 [0.03189601 0.03356563]
 [0.02940074 0.03122527]
 [0.02232039 0.02401968]
 [0.03122794 0.03206578]
 [0.03024414 0.03211467]
 [0.02888487 0.03098044]
 [0.03016075 0.03258503]
 [0.03441442 0.03390123]
 [0.02752374 0.03042162]
 [0.35442824 0.02435757]
 [0.02871903 0.03090021]
 [0.3593691  0.02913966]
 [0.03324658 0.03550407]
 [0.03404835 0.03722015]
 [0.02882221 0.03141782]
 [0.35947463 0.02837149]
 [0.01924021 0.02016985]
 [0.03011126 0.03240521]
 [0.02823934 0.03027398]
 [0.03197743 0.03457547]
 [0.02607648 0.02799856]
 [0.03079991 0.03320382]
 [0.02585926 0.02779587]
 [0.03249593 0.03505561]
 [0.03381437 0.03688468]
